  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.3.2
    environment:
      - http.host=0.0.0.0
      - transport.host=127.0.0.1
      - cluster.name=prototype-docker
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - es:/usr/share/elasticsearch/5.3.2/
  kibana:
    image: docker.elastic.co/kibana/kibana:5.3.2
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch.jessebenson.me:9200/
    ports:
      - 5601:5601